name: glue-mnli

datasets:
  _target_: datasets.load_dataset
  path: glue
  name: mnli

preprocessor:
  _target_: peta.tasks.MNLI_Preprocessor

map_kwargs:
  remove_columns: ["idx", "hypothesis", "premise", "label"]
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
