name: glue-qnli

datasets:
  _target_: datasets.load_dataset
  path: glue
  name: qnli

preprocessor:
  _target_: peta.tasks.QNLI_Preprocessor

map_kwargs:
  remove_columns: ["question", "sentence", "idx"]
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
