name: GTSRB

datamodule:
  _target_: peta.datamodules.GTSRBDataModule
  root: data
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  pin_memory: false
  train_transform: null
  test_transform: null
